//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musteriler_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler_TBL()
        {
            this.Satislar_TBL = new HashSet<Satislar_TBL>();
        }
    
        public int MusteriID { get; set; }

        [Required(ErrorMessage = "Lütfen müþteri adýný giriniz.")] //=> Müþteri adý ve soyadý için doðrulama iþlemlerinde mesaj girildi.
        [StringLength(50, ErrorMessage = "Ad alaný 50 karakteri geçemez.")]
        public string MusteriAd { get; set; }

        [Required(ErrorMessage = "Lütfen müþteri soyadýný giriniz.")]
        [StringLength(50, ErrorMessage = "Soyad alaný 50 karakteri geçemez.")]
        public string MusteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar_TBL> Satislar_TBL { get; set; }
    }
}
