//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler_TBL()
        {
            this.Satislar_TBL = new HashSet<Satislar_TBL>();
        }
    
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public string UrunMarka { get; set; }
        public short UrunKategori { get; set; }
        public decimal Fiyat { get; set; }
        public int Stok { get; set; }
    
        public virtual Kategoriler_TBL Kategoriler_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar_TBL> Satislar_TBL { get; set; }
    }
}
